import React,{useEffect,useState} from 'react';
import {createRoot} from 'react-dom/client';
import axios from 'axios';
import './style.css';

const API=import.meta.env.VITE_API_URL||'http://localhost:4000/api';
const api=axios.create({baseURL:API});
api.interceptors.request.use(c=>{const t=localStorage.getItem('token');if(t)c.headers.Authorization=`Bearer ${t}`;return c});

function Auth({onLogin}){
 const [mode,setMode]=useState('login'),[form,setForm]=useState({name:'',email:'',password:''}),[msg,setMsg]=useState(''),[loading,setLoading]=useState(false);
 const submit=async e=>{e.preventDefault();setMsg('');setLoading(true);try{const url=mode==='login'?'/auth/login':'/auth/register';const r=await api.post(url,form);if(mode==='login'){localStorage.setItem('token',r.data.token);onLogin()}else{setMode('login');setMsg('Registration successful. Please login.')}}catch(e){setMsg(e.response?.data?.message||'Something went wrong')}finally{setLoading(false)}};
 return <div className="auth"><div className="auth-card"><div className="brand">Student<span>Admin</span></div><h1>{mode==='login'?'Welcome back':'Create account'}</h1><p className="muted">Student Management System</p><form onSubmit={submit}>{mode==='register'&&<input placeholder="Name" required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/>}<input type="email" placeholder="Email" required value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/><input type="password" placeholder="Password" minLength="6" required value={form.password} onChange={e=>setForm({...form,password:e.target.value})}/>{msg&&<div className="alert">{msg}</div>}<button disabled={loading}>{loading?'Please wait...':mode==='login'?'Login':'Register'}</button></form><button className="link" onClick={()=>{setMode(mode==='login'?'register':'login');setMsg('')}}>{mode==='login'?'Create a new account':'Already have an account? Login'}</button></div></div>
}

function Dashboard({logout}){
 const empty={name:'',email:'',phone:'',age:'',course:''};const [students,setStudents]=useState([]),[form,setForm]=useState(empty),[editing,setEditing]=useState(null),[search,setSearch]=useState(''),[msg,setMsg]=useState(''),[loading,setLoading]=useState(false);
 const load=async()=>{try{setLoading(true);const r=await api.get('/students');setStudents(r.data.students||[])}catch(e){if(e.response?.status===401||e.response?.status===403)logout();else setMsg(e.response?.data?.message||'Failed to load students')}finally{setLoading(false)}};
 useEffect(()=>{load()},[]);
 const submit=async e=>{e.preventDefault();setMsg('');try{if(editing)await api.put(`/students/${editing}`,form);else await api.post('/students',{...form,age:form.age?Number(form.age):undefined});setForm(empty);setEditing(null);load()}catch(e){setMsg(e.response?.data?.message||'Save failed')}};
 const edit=s=>{setEditing(s._id);setForm({name:s.name||'',email:s.email||'',phone:s.phone||'',age:s.age||'',course:s.course||''});window.scrollTo({top:0,behavior:'smooth'})};
 const del=async id=>{if(!confirm('Delete this student?'))return;try{await api.delete(`/students/${id}`);load()}catch(e){setMsg(e.response?.data?.message||'Delete failed')}};
 const filtered=students.filter(s=>[s.name,s.email,s.phone,s.course].join(' ').toLowerCase().includes(search.toLowerCase()));
 return <div className="app"><header><div className="brand">Student<span>Admin</span></div><div className="header-right"><span>{students.length} Students</span><button className="logout" onClick={logout}>Logout</button></div></header><main><section className="hero"><div><h1>Student Management</h1><p>Add, update and manage student records.</p></div></section><section className="panel"><div className="panel-title"><h2>{editing?'Edit Student':'Add Student'}</h2>{editing&&<button className="secondary" onClick={()=>{setEditing(null);setForm(empty)}}>Cancel</button>}</div><form className="grid-form" onSubmit={submit}><input placeholder="Student name *" required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/><input type="email" placeholder="Email *" required value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/><input placeholder="Phone" value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/><input type="number" min="1" placeholder="Age" value={form.age} onChange={e=>setForm({...form,age:e.target.value})}/><input placeholder="Course" value={form.course} onChange={e=>setForm({...form,course:e.target.value})}/><button>{editing?'Update Student':'Add Student'}</button></form>{msg&&<div className="alert">{msg}</div>}</section><section className="panel"><div className="table-head"><h2>Students</h2><input className="search" placeholder="Search students..." value={search} onChange={e=>setSearch(e.target.value)}/></div><div className="table-wrap"><table><thead><tr><th>Name</th><th>Email</th><th>Phone</th><th>Age</th><th>Course</th><th>Actions</th></tr></thead><tbody>{loading?<tr><td colSpan="6" className="empty">Loading...</td></tr>:filtered.length===0?<tr><td colSpan="6" className="empty">No students found</td></tr>:filtered.map(s=><tr key={s._id}><td><strong>{s.name}</strong></td><td>{s.email}</td><td>{s.phone||'-'}</td><td>{s.age||'-'}</td><td><span className="tag">{s.course||'N/A'}</span></td><td><button className="small" onClick={()=>edit(s)}>Edit</button><button className="small danger" onClick={()=>del(s._id)}>Delete</button></td></tr>)}</tbody></table></div></section></main></div>
}
function App(){const [auth,setAuth]=useState(!!localStorage.getItem('token'));const logout=()=>{localStorage.removeItem('token');setAuth(false)};return auth?<Dashboard logout={logout}/>:<Auth onLogin={()=>setAuth(true)}/>}
createRoot(document.getElementById('root')).render(<App/>);
