import { useEffect, useState } from 'react';
import { Link, useLocation, useNavigate } from 'react-router-dom';
import { authApi } from '../api';
import { useAuth } from '../context/AuthContext';
export default function VerifyOtp(){
 const loc=useLocation();const nav=useNavigate();const {login}=useAuth();const [email,setEmail]=useState(loc.state?.email||'');const [otp,setOtp]=useState(loc.state?.devOtp||'');const [error,setError]=useState('');const [message,setMessage]=useState(loc.state?.devOtp?`Development OTP: ${loc.state.devOtp}`:'');
 useEffect(()=>{if(!email){}},[email]);
 const verify=async e=>{e.preventDefault();setError('');try{const {data}=await authApi.verifyOtp({email,otp}); localStorage.setItem('travello_token',data.token); const me=await authApi.me(); login({token:data.token,data:{user:me.data.data.user}});nav('/tours')}catch(e){setError(e.response?.data?.message||'Verification failed')}};
 const resend=async()=>{setError('');try{const {data}=await authApi.resendOtp({email});setMessage(`Development OTP: ${data.devOtp}`)}catch(e){setError(e.response?.data?.message||'Could not resend OTP')}};
 return <div className="auth-wrap"><div className="auth-card"><h2>Verify your email</h2><p>Enter the 6-digit OTP generated by the backend.</p><form onSubmit={verify}>{error&&<div className="alert error">{error}</div>}{message&&<div className="alert success">{message}</div>}<label>Email<input type="email" required value={email} onChange={e=>setEmail(e.target.value)}/></label><label>OTP<input inputMode="numeric" maxLength="6" required value={otp} onChange={e=>setOtp(e.target.value.replace(/\D/g,''))}/></label><button className="btn primary full">Verify account</button></form><button className="text-btn" onClick={resend}>Resend OTP</button><p className="form-foot"><Link to="/login">Back to login</Link></p></div></div>
}
